version: '3'
services:
  web:
    image: php
    ports:
      - '8080:80'
    volumes:
      - ./htdocs:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${LOCAL_DB_USR:-broiler_plate}
      DB_PASSWORD: ${LOCAL_DB_PWD:-broiler_plate}
      DB_DATABASE: ${LOCAL_DB_DB:-broiler_plate}
    links:
      - db
  db:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${LOCAL_DB_USR:-broiler_plate}
      MYSQL_PASSWORD: ${LOCAL_DB_PWD:-broiler_plate}
      MYSQL_DATABASE: ${LOCAL_DB_DB:-broiler_plate}
